### PR TITLE
Completed todo app project's basic requirements

### PR DESCRIPTION
**Pull request by cyonii**
I have built a todo app following the basic requirement from [Odin Project](https://www.theodinproject.com/paths/full-stack-javascript/courses/javascript/lessons/todo-list). In this build I have completed the todo app to carry out basic functionalities to let users create and manage projects and new tasks.
In this build users can do the following:
- can add projects
- can create new tasks

Projects and task data are saved on users local machines until they're deleted.
I have also built the web UI for this app.

### CODE REVIEW

**Review by trekab — CHANGES_REQUESTED** [review]
#### Changes Required! :recycle: 
Hi @cyonii! Unfortunately, I am unable to review most of your changes because the app returns an error when I try to run it. The image below shows the error and the output I see on my end.

Screenshot

I am unable to submit any input. Try to fix this. It would also be nice if you:
- [ ] __[Optional]__ Deploy your app and share the link to the deployed version in the `README.md` file. Your current live link returns a `404` error.

__Please make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink: 
__Treasure Kabareebe__
[Portfolio](https://trekab.github.io) | [LinkedIn](https://www.linkedin.com/in/treasure-kabareebe/) | [Twitter](https://twitter.com/TKabareebe)

**Comment by cyonii** [comment]
I deleted my local copy of this repo and downloaded a fresh one from Github, I followed the instruction on my README and the code works just fine.

Could you please give me the specifics of the actions that triggered this error, so that I can try and reproduce it 🤒 .
Regards 🤓 .

**Comment by cyonii** [comment]
Hello @trekab, thank you for the review.

I deleted my local copy of this repo and downloaded a fresh one from Github, I followed the instruction on my README and the code works just fine.

Could you please give me the specifics of the actions that triggered this error, so that I can try and reproduce it 🤒 .
Regards 🤓 .

**Review by voscarmv — CHANGES_REQUESTED** [review]
# Impressive work.  💻 👀 ✨
- Excellent input validation.
- Great design: simple, slick, and easy to understand.
- Great use of animation to make your design more dynamic.
- Excellent code modulation. I love how your DOM methods are separate from the project's logic. Great work there.


## However, there are some changes required 👀 🧰 🔨 🔧
- Please provide a way for the user to delete and edit tasks.
- The tasks don't show their priority anywhere. Please add a priority display for the tasks.



### Submit these changes and request a new code review! 😄 👍

### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier)🧑‍💻🗨️🧑‍💻
# Happy Coding! 🧠 ⌨️ 🖱️ 🖥️

**Comment by cyonii** [comment]
@voscarmv, thank you for this awesome review 😇

**Review by Torres-ssf — CHANGES_REQUESTED** [review]
### Changes Required :muscle: 
Hi @cyonii :hand: 
Nice job on this project so far. But we need to make some changes before moving on.

- [ ]  Webpack it's not compiling at my side. I tried to follow the instructions in the README file but I'm getting the same error every time. I tried the 3 available scripts. Is it working properly at your side?
Screenshot from 2021-04-07 13-13-03

I checked the live version and it seems that every requested change was implemented, nicely done :clap: :+1: 

Happy coding :computer: 
**Sérgio Torres**

**Comment by cyonii** [comment]
Hello @Torres-ssf, did you run `npm install`?
Because according to the screenshot you shared it says it couldn't find `node_modules`

**Review by Temmarie — CHANGES_REQUESTED** [review]
## Changes Required! :recycle:

### Hi @cyonii      ! :wave: :wave:

#### Thank you for implementing the previously required changes. However, there are still changes required for you to make in order for your project to be approved.
- - -

### **Recommended**

- [ ] As stated by the previous TSE, the tasks don't show their priority anywhere. Please add a priority display for the tasks.
- [ ] I could not add an item to the task when I ran the project locally. It was not clickable.

__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink:
__Grace Tamara Ekunola __
[GitHub](https://github.com/temmarie) | [LinkedIn](https://www.linkedin.com/in/ekunola-grace/) | [Twitter](https://twitter.com/TemmarieW)

**Comment by cyonii** [comment]
Hello @Temmari, thank you for the review. However, I need a few clarifications please.

- The priority is displayed at the bottom right of the task card. See screenshot image
- I have downloaded and run the app again and it works for me on all browsers. Are you experiencing the same error on both the live and local versions ?

**Comment by cyonii** [comment]
Also, when you click it, does it output anything on the browser’s console?

**Comment by Torres-ssf** [comment]
> Hello @Torres-ssf, did you run `npm install`?
> Because according to the screenshot you shared it says it couldn't find `node_modules`

Yes @cyonii, I tried both with NPM and with Yarn. Neither of them worked. Maybe it was only at my side

**Comment by cyonii** [comment]
> > Hello @Torres-ssf, did you run `npm install`?
> 
> > Because according to the screenshot you shared it says it couldn't find `node_modules`
> 
> 
> 
> Yes @cyonii, I tried both with NPM and with Yarn. Neither of them worked. Maybe it was only at my side

I would guess so because I didn't make any changes as I couldn't reproduce the error on my end, and it seems it worked fine for the other Reviewer. ✌️

**Review by wathigo — APPROVED** [review]
## APPROVED :heavy_check_mark: 
Great job implementing the suggested changes.

**You may proceed to the next milestone.**

**Happy Coding :computer: 
Simon Wathigo**

**Comment by Temmarie** [comment]
> Hello @Temmari, thank you for the review. However, I need a few clarifications please.
> 
> * The priority is displayed at the bottom right of the task card. See screenshot image
> * I have downloaded and run the app again and it works for me on all browsers. Are you experiencing the same error on both the live and local versions ?

It only had that error locally, I didn't see this feature you have posted here. Good job!

**Pull request merged**
